//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSide
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRepeatedTask
    {
        public int taskId { get; set; }
        public string operatin { get; set; }
        public string deviceMac { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<int> repeatEvery { get; set; }
    
        public virtual tblPlug tblPlug { get; set; }
    }
}
