//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSide
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlug()
        {
            this.tblOneTimeTasks = new HashSet<tblOneTimeTask>();
            this.tblRepeatedTasks = new HashSet<tblRepeatedTask>();
        }
    
        public string mac { get; set; }
        public string nickNmae { get; set; }
        public string userName { get; set; }
        public bool isOn { get; set; }
        public string priority { get; set; }
        public bool approved { get; set; }
        public Nullable<int> sampleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOneTimeTask> tblOneTimeTasks { get; set; }
        public virtual tblPowerUsageSample tblPowerUsageSample { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRepeatedTask> tblRepeatedTasks { get; set; }
    }
}
